// This file is auto-generated by @hey-api/openapi-ts

export type ApplyEditRequest = {
    codeEdit: string;
    model?: string;
};

export type ApplyEditResponse = {
    message?: string;
    originalContent?: string;
    path?: string;
    provider?: string;
    success?: boolean;
    updatedContent?: string;
};

export type ArchiveManifest = {
    /**
     * Added and Modified count the archive's payload members.
     */
    added?: number;
    /**
     * APIVersion is the sandbox-api build that produced the archive.
     */
    apiVersion?: string;
    createdAt: string;
    /**
     * Deleted are paths the image has and the sandbox deleted. Tar cannot carry
     * a deletion, so import applies these from the manifest.
     */
    deleted?: Array<string>;
    /**
     * Excludes are the paths left out of the comparison.
     */
    excludes?: Array<string>;
    /**
     * ImageDevice is the device the pristine image was read from, for the record:
     * it says where the sandbox that exported the archive found its image.
     */
    imageDevice?: string;
    modified?: number;
    /**
     * PayloadBytes is the total content size of the payload members.
     */
    payloadBytes?: number;
    /**
     * Processes tells whether ProcessesName is present.
     */
    processes?: boolean;
    /**
     * Root is the directory the paths are relative to.
     */
    root: string;
    version: number;
};

export type ContentSearchMatch = {
    column: number;
    context?: string;
    line: number;
    path: string;
    text: string;
};

export type ContentSearchResponse = {
    matches: Array<ContentSearchMatch>;
    query: string;
    total: number;
};

export type Directory = {
    files: Array<File>;
    name: string;
    path: string;
    /**
     * @name Subdirectories
     */
    subdirectories: Array<Subdirectory>;
};

export type DriveListResponse = {
    mounts?: Array<DriveMountInfo>;
};

export type DriveMountInfo = {
    driveName?: string;
    drivePath?: string;
    /**
     * The local GID used for this mount
     */
    gidMap?: string;
    mountPath?: string;
    readOnly?: boolean;
    /**
     * The local UID used for this mount
     */
    uidMap?: string;
};

export type DriveMountRequest = {
    driveName: string;
    /**
     * Optional, defaults to "/"
     */
    drivePath?: string;
    /**
     * Optional, local GID to map (filer GID is always 0)
     */
    gidMap?: string;
    mountPath: string;
    /**
     * Optional, defaults to false
     */
    readOnly?: boolean;
    /**
     * Optional, local UID to map (filer UID is always 0)
     */
    uidMap?: string;
};

export type DriveMountResponse = {
    driveName?: string;
    drivePath?: string;
    /**
     * The local GID used for this mount
     */
    gidMap?: string;
    message?: string;
    mountPath?: string;
    readOnly?: boolean;
    success?: boolean;
    /**
     * The local UID used for this mount
     */
    uidMap?: string;
};

export type DriveUnmountResponse = {
    message?: string;
    mountPath?: string;
    success?: boolean;
};

export type ErrorResponse = {
    error: string;
};

export type ExportOptions = {
    /**
     * Async starts the export and answers immediately, leaving it to run: an
     * archive of a large filesystem takes longer than a request may be held
     * open. Its progress is reported by /archive/status.
     */
    async?: boolean;
    /**
     * DryRun reports what would be archived, and its exact size, without
     * stopping anything and without uploading.
     */
    dryRun?: boolean;
    /**
     * Excludes are added to the paths excluded by default.
     */
    excludes?: Array<string>;
    /**
     * Headers are sent with the upload request as given. A presigned URL only
     * accepts the headers it was signed for, so these have to match what the
     * caller signed: sending one that was not signed, or signing one that is not
     * sent, is rejected as a signature mismatch. Typical use is a storage class,
     * x-amz-storage-class: GLACIER_IR.
     */
    headers?: {
        [key: string]: string;
    };
    /**
     * ImageDevice is the device holding the pristine image. It is found on its
     * own, wherever the sandbox booted from attached it, and naming one here
     * only overrides that.
     */
    imageDevice?: string;
    /**
     * ImageMountPoint is a directory where the pristine image is already mounted.
     * When set the image device is neither mounted nor unmounted.
     */
    imageMountPoint?: string;
    /**
     * Multipart uploads the archive part by part instead, which is how an
     * archive larger than the 5 GB a single PUT accepts is stored. It takes
     * precedence over URL.
     */
    multipart?: MultipartUpload;
    /**
     * SaveProcesses stores the process list in the archive so restore can
     * relaunch the workload. Defaults to true; set it to false to archive
     * storage only.
     */
    saveProcesses?: boolean;
    /**
     * StopTimeoutSeconds bounds the graceful stop of each process.
     */
    stopTimeoutSeconds?: number;
    /**
     * URL is a presigned S3 PUT URL the archive is streamed to. Empty is only
     * valid with DryRun, or with Multipart.
     */
    url?: string;
};

export type ExportProgress = {
    /**
     * Error is why the export failed, without the presigned URL it used.
     */
    error?: string;
    finishedAt?: string;
    /**
     * Size is the archive's exact size, known once the filesystem is scanned.
     */
    size?: number;
    startedAt?: string;
    state?: ArchiveExportState;
    /**
     * Uploaded reports whether the storage holds the archive.
     */
    uploaded?: boolean;
};

export type ExportResult = {
    /**
     * Changes lists every path in the archive. Only filled for a dry run,
     * where it is the point of the call.
     */
    changes?: Array<ArchiveChange>;
    duration?: string;
    manifest: ArchiveManifest;
    /**
     * Size is the exact number of bytes uploaded, known before the upload
     * starts since the archive is not compressed.
     */
    size?: number;
    /**
     * StoppedProcesses are the processes stopped to freeze the filesystem.
     */
    stoppedProcesses?: Array<string>;
    /**
     * Uploaded is false for a dry run.
     */
    uploaded?: boolean;
};

export type File = {
    group: string;
    lastModified: string;
    name: string;
    owner: string;
    path: string;
    permissions: string;
    size: number;
};

export type FileRequest = {
    content?: string;
    isDirectory?: boolean;
    permissions?: string;
};

export type FileWithContent = {
    content: string;
    group: string;
    lastModified: string;
    name: string;
    owner: string;
    path: string;
    permissions: string;
    size: number;
};

export type FindMatch = {
    path: string;
    /**
     * "file" or "directory"
     */
    type: string;
};

export type FindResponse = {
    matches: Array<FindMatch>;
    total: number;
};

export type FuzzySearchMatch = {
    path: string;
    score: number;
    /**
     * "file" or "directory"
     */
    type: string;
};

export type FuzzySearchResponse = {
    matches: Array<FuzzySearchMatch>;
    total: number;
};

export type HealthResponse = {
    arch: string;
    buildTime: string;
    gitCommit: string;
    goVersion: string;
    lastUpgrade: UpgradeStatus;
    os: string;
    startedAt: string;
    status: string;
    upgradeCount: number;
    uptime: string;
    uptimeSeconds: number;
    version: string;
};

export type MultipartCompleteRequest = {
    parts?: Array<MultipartPartInfo>;
};

export type MultipartInitiateRequest = {
    permissions?: string;
};

export type MultipartInitiateResponse = {
    path?: string;
    uploadId?: string;
};

export type MultipartListPartsResponse = {
    parts?: Array<FilesystemUploadedPart>;
    uploadId?: string;
};

export type MultipartListUploadsResponse = {
    uploads?: Array<FilesystemMultipartUpload>;
};

export type MultipartPartInfo = {
    etag?: string;
    partNumber?: number;
};

export type MultipartUpload = {
    /**
     * AbortURL is a presigned DELETE URL that discards the parts already
     * uploaded. Without it a failed export leaves them on the storage until a
     * lifecycle rule removes them.
     */
    abortUrl?: string;
    /**
     * CompleteURL is a presigned POST URL that assembles the parts.
     */
    completeUrl?: string;
    /**
     * PartSize is the number of bytes sent to every part but the last.
     */
    partSize?: number;
    /**
     * PartURLs are presigned PUT URLs, one per part, in order. Extra ones are
     * left unused.
     */
    partUrls?: Array<string>;
};

export type MultipartUploadPartResponse = {
    etag?: string;
    partNumber?: number;
    size?: number;
};

export type PortMonitorRequest = {
    /**
     * URL to call when a new port is detected
     */
    callback?: string;
};

export type ProcessLogs = {
    logs: string;
    stderr: string;
    stdout: string;
};

export type ProcessRequest = {
    command: string;
    env?: {
        [key: string]: string;
    };
    /**
     * Disable scale-to-zero while process runs. Default timeout is 600s (10 minutes). Set timeout to 0 for infinite.
     */
    keepAlive?: boolean;
    /**
     * Maximum number of restarts on failure. Set to a negative value (e.g. -1) for unlimited restarts.
     */
    maxRestarts?: number;
    name?: string;
    restartOnFailure?: boolean;
    /**
     * Open a writable stdin pipe, fed via POST /process/{identifier}/stdin and closed via DELETE. The pipe does not survive a sandbox-api restart: the process then sees EOF.
     */
    stdin?: boolean;
    /**
     * Timeout in seconds. When keepAlive is true, defaults to 600s (10 minutes). Set to 0 for infinite (no auto-kill).
     */
    timeout?: number;
    waitForCompletion?: boolean;
    waitForPorts?: Array<number>;
    workingDir?: string;
};

export type ProcessResponse = {
    command: string;
    completedAt: string;
    exitCode: number;
    /**
     * Whether scale-to-zero is disabled for this process
     */
    keepAlive?: boolean;
    logs: string;
    maxRestarts?: number;
    name: string;
    pid: string;
    restartCount?: number;
    restartOnFailure?: boolean;
    startedAt: string;
    status: 'failed' | 'killed' | 'stopped' | 'running' | 'completed';
    stderr: string;
    /**
     * Whether the process was started with a writable stdin pipe
     */
    stdin?: boolean;
    stdout: string;
    workingDir: string;
};

export type QuiesceStatus = {
    /**
     * Export reports the export started asynchronously, if there was one. It is
     * how a caller that did not wait for the export learns that the archive is
     * on the storage, or why it is not.
     */
    export?: ExportProgress;
    /**
     * ReadOnlyRoot reports whether the root mount was remounted read-only, which
     * is what actually stops writes; false means the freeze relies only on the
     * API refusing calls, and the reason says why.
     */
    readOnlyRoot?: boolean;
    /**
     * Reason is a human readable explanation of why the sandbox is frozen.
     */
    reason?: string;
    /**
     * Restore reports the archive this sandbox was started from, if it was
     * started from one: how far its restore has got, and how it ended.
     */
    restore?: RestoreProgress;
    /**
     * Since is when the sandbox left StateActive.
     */
    since?: string;
    state: ArchiveQuiesceState;
    /**
     * StoppedProcesses are the process identifiers stopped while quiescing.
     */
    stoppedProcesses?: Array<string>;
};

export type RankedFile = {
    content?: string;
    path?: string;
    score?: number;
};

export type RerankingResponse = {
    files?: Array<RankedFile>;
    message?: string;
    success?: boolean;
};

export type RestoreProgress = {
    deleted?: number;
    /**
     * Downloaded is how much of the archive has been read so far.
     */
    downloaded?: number;
    /**
     * Error is why the restore failed, without the presigned URL it used.
     */
    error?: string;
    finishedAt?: string;
    /**
     * Restored and Deleted count what the archive changed on the filesystem.
     */
    restored?: number;
    /**
     * Size is the archive's size as the storage announced it, and zero when it
     * announced none - a client showing a percentage has to allow for that.
     */
    size?: number;
    startedAt?: string;
    state?: ArchiveRestoreState;
};

export type Subdirectory = {
    name: string;
    path: string;
};

export type SuccessResponse = {
    message: string;
    path?: string;
};

export type TreeRequest = {
    files?: {
        [key: string]: string;
    };
};

export type TunnelConfigRequest = {
    /**
     * Base64-encoded tunnel config JSON
     */
    config: string;
};

export type UpgradeRequest = {
    /**
     * Base URL for releases (useful for forks)
     */
    baseUrl?: string;
    /**
     * Version to upgrade to: "latest" (default), "develop", "main", or specific tag like "v1.0.0"
     */
    version?: string;
};

export type UpgradeStatus = {
    /**
     * Path to downloaded binary
     */
    binaryPath?: string;
    /**
     * Bytes downloaded
     */
    bytesDownloaded?: number;
    /**
     * URL used for download
     */
    downloadUrl?: string;
    /**
     * Error message if failed
     */
    error?: string;
    /**
     * When the upgrade was attempted
     */
    lastAttempt?: string;
    /**
     * Current state (idle, running, completed, failed)
     */
    status: ProcessUpgradeState;
    /**
     * Current/last step (none, starting, download, validate, replace, completed, skipped)
     */
    step: string;
    /**
     * Version being upgraded to
     */
    version: string;
};

export type ArchiveChange = {
    kind: ArchiveChangeKind;
    /**
     * Path is relative to the root, without a leading slash.
     */
    path: string;
    /**
     * Size is the file content size in bytes, 0 for anything but a regular file.
     */
    size?: number;
};

export type ArchiveChangeKind = 'added' | 'modified' | 'deleted';

export type ArchiveExportState = 'running' | 'succeeded' | 'failed';

export type ArchiveQuiesceState = 'active' | 'quiescing' | 'quiesced' | 'restoring';

export type ArchiveRestoreState = 'downloading' | 'extracting' | 'relaunching' | 'succeeded' | 'failed';

export type FilesystemMultipartUpload = {
    initiatedAt?: string;
    parts?: {
        [key: string]: FilesystemUploadedPart;
    };
    path?: string;
    permissions?: number;
    uploadId?: string;
};

export type FilesystemUploadedPart = {
    etag?: string;
    partNumber?: number;
    size?: number;
    uploadedAt?: string;
};

export type HandlerReloadResponse = {
    applied?: number;
    generation?: number;
    removed?: number;
};

export type ProcessUpgradeState = 'idle' | 'running' | 'completed' | 'failed';

export type PostArchiveExportData = {
    /**
     * Export options
     */
    body: ExportOptions;
    path?: never;
    query?: never;
    url: '/archive/export';
};

export type PostArchiveExportErrors = {
    /**
     * Invalid request
     */
    400: ErrorResponse;
    /**
     * An export is already in progress
     */
    409: ErrorResponse;
    /**
     * Export failed
     */
    500: ErrorResponse;
};

export type PostArchiveExportError = PostArchiveExportErrors[keyof PostArchiveExportErrors];

export type PostArchiveExportResponses = {
    /**
     * Export result
     */
    200: ExportResult;
    /**
     * The export was started and runs in the background
     */
    202: ExportProgress;
};

export type PostArchiveExportResponse = PostArchiveExportResponses[keyof PostArchiveExportResponses];

export type PostArchiveResumeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/archive/resume';
};

export type PostArchiveResumeErrors = {
    /**
     * An export or a restore is in progress
     */
    409: ErrorResponse;
    /**
     * The root filesystem could not be made writable again
     */
    500: ErrorResponse;
};

export type PostArchiveResumeError = PostArchiveResumeErrors[keyof PostArchiveResumeErrors];

export type PostArchiveResumeResponses = {
    /**
     * Archive status
     */
    200: QuiesceStatus;
};

export type PostArchiveResumeResponse = PostArchiveResumeResponses[keyof PostArchiveResumeResponses];

export type GetArchiveStatusData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/archive/status';
};

export type GetArchiveStatusResponses = {
    /**
     * Archive status
     */
    200: QuiesceStatus;
};

export type GetArchiveStatusResponse = GetArchiveStatusResponses[keyof GetArchiveStatusResponses];

export type PutCodegenFastapplyByPathData = {
    /**
     * Code edit request
     */
    body: ApplyEditRequest;
    path: {
        /**
         * Path to the file to edit (relative to workspace)
         */
        path: string;
    };
    query?: never;
    url: '/codegen/fastapply/{path}';
};

export type PutCodegenFastapplyByPathErrors = {
    /**
     * Invalid request
     */
    400: ErrorResponse;
    /**
     * Unprocessable entity - failed to process the request
     */
    422: ErrorResponse;
    /**
     * Service unavailable - no provider configured
     */
    503: ErrorResponse;
};

export type PutCodegenFastapplyByPathError = PutCodegenFastapplyByPathErrors[keyof PutCodegenFastapplyByPathErrors];

export type PutCodegenFastapplyByPathResponses = {
    /**
     * Code edit applied successfully
     */
    200: ApplyEditResponse;
};

export type PutCodegenFastapplyByPathResponse = PutCodegenFastapplyByPathResponses[keyof PutCodegenFastapplyByPathResponses];

export type GetCodegenRerankingByPathData = {
    body?: never;
    path: {
        /**
         * Path to search in (relative to workspace)
         */
        path: string;
    };
    query: {
        /**
         * Natural language query to search for
         */
        query: string;
        /**
         * Minimum relevance score (default: 0.5)
         */
        scoreThreshold?: number;
        /**
         * Maximum tokens to return (default: 30000)
         */
        tokenLimit?: number;
        /**
         * Regex pattern to filter files (e.g., .*\\.ts$ for TypeScript files)
         */
        filePattern?: string;
    };
    url: '/codegen/reranking/{path}';
};

export type GetCodegenRerankingByPathErrors = {
    /**
     * Invalid request
     */
    400: ErrorResponse;
    /**
     * Unprocessable entity - failed to process the request
     */
    422: ErrorResponse;
    /**
     * Service unavailable - Relace not configured
     */
    503: ErrorResponse;
};

export type GetCodegenRerankingByPathError = GetCodegenRerankingByPathErrors[keyof GetCodegenRerankingByPathErrors];

export type GetCodegenRerankingByPathResponses = {
    /**
     * Relevant files found
     */
    200: RerankingResponse;
};

export type GetCodegenRerankingByPathResponse = GetCodegenRerankingByPathResponses[keyof GetCodegenRerankingByPathResponses];

export type GetDrivesMountData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/drives/mount';
};

export type GetDrivesMountErrors = {
    /**
     * Internal Server Error
     */
    500: ErrorResponse;
};

export type GetDrivesMountError = GetDrivesMountErrors[keyof GetDrivesMountErrors];

export type GetDrivesMountResponses = {
    /**
     * OK
     */
    200: DriveListResponse;
};

export type GetDrivesMountResponse = GetDrivesMountResponses[keyof GetDrivesMountResponses];

export type PostDrivesMountData = {
    /**
     * Drive attachment parameters
     */
    body: DriveMountRequest;
    path?: never;
    query?: never;
    url: '/drives/mount';
};

export type PostDrivesMountErrors = {
    /**
     * Bad Request
     */
    400: ErrorResponse;
    /**
     * Forbidden
     */
    403: ErrorResponse;
    /**
     * Conflict
     */
    409: ErrorResponse;
    /**
     * Internal Server Error
     */
    500: ErrorResponse;
};

export type PostDrivesMountError = PostDrivesMountErrors[keyof PostDrivesMountErrors];

export type PostDrivesMountResponses = {
    /**
     * OK
     */
    200: DriveMountResponse;
};

export type PostDrivesMountResponse = PostDrivesMountResponses[keyof PostDrivesMountResponses];

export type DeleteDrivesMountByMountPathData = {
    body?: never;
    path: {
        /**
         * Mount path to detach (must start with /, e.g. /mnt/test)
         */
        mountPath: string;
    };
    query?: never;
    url: '/drives/mount/{mountPath}';
};

export type DeleteDrivesMountByMountPathErrors = {
    /**
     * Bad Request
     */
    400: ErrorResponse;
    /**
     * Internal Server Error
     */
    500: ErrorResponse;
};

export type DeleteDrivesMountByMountPathError = DeleteDrivesMountByMountPathErrors[keyof DeleteDrivesMountByMountPathErrors];

export type DeleteDrivesMountByMountPathResponses = {
    /**
     * OK
     */
    200: DriveUnmountResponse;
};

export type DeleteDrivesMountByMountPathResponse = DeleteDrivesMountByMountPathResponses[keyof DeleteDrivesMountByMountPathResponses];

export type PostEnvironmentReloadData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/environment/reload';
};

export type PostEnvironmentReloadErrors = {
    /**
     * Not Found
     */
    404: ErrorResponse;
    /**
     * Internal Server Error
     */
    500: ErrorResponse;
};

export type PostEnvironmentReloadError = PostEnvironmentReloadErrors[keyof PostEnvironmentReloadErrors];

export type PostEnvironmentReloadResponses = {
    /**
     * OK
     */
    200: HandlerReloadResponse;
};

export type PostEnvironmentReloadResponse = PostEnvironmentReloadResponses[keyof PostEnvironmentReloadResponses];

export type GetFilesystemContentSearchByPathData = {
    body?: never;
    path: {
        /**
         * Directory path to search in
         */
        path: string;
    };
    query: {
        /**
         * Text to search for
         */
        query: string;
        /**
         * Case sensitive search (default: false)
         */
        caseSensitive?: boolean;
        /**
         * Maximum number of results to return (default: 100)
         */
        maxResults?: number;
        /**
         * File pattern to include (e.g., *.go)
         */
        filePattern?: string;
        /**
         * Comma-separated directory names to skip (default: node_modules,vendor,.git,dist,build,target,__pycache__,.venv,.next,coverage)
         */
        excludeDirs?: string;
    };
    url: '/filesystem-content-search/{path}';
};

export type GetFilesystemContentSearchByPathErrors = {
    /**
     * Bad request
     */
    400: ErrorResponse;
    /**
     * Unprocessable entity
     */
    422: ErrorResponse;
    /**
     * Internal server error
     */
    500: ErrorResponse;
};

export type GetFilesystemContentSearchByPathError = GetFilesystemContentSearchByPathErrors[keyof GetFilesystemContentSearchByPathErrors];

export type GetFilesystemContentSearchByPathResponses = {
    /**
     * Content search results
     */
    200: ContentSearchResponse;
};

export type GetFilesystemContentSearchByPathResponse = GetFilesystemContentSearchByPathResponses[keyof GetFilesystemContentSearchByPathResponses];

export type GetFilesystemFindByPathData = {
    body?: never;
    path: {
        /**
         * Path to search in (e.g., /home/user/projects)
         */
        path: string;
    };
    query?: {
        /**
         * Type of search (file or directory)
         */
        type?: string;
        /**
         * Comma-separated file patterns to include (e.g., *.go,*.js)
         */
        patterns?: string;
        /**
         * Maximum number of results to return (default: 20). If set to 0, all results will be returned.
         */
        maxResults?: number;
        /**
         * Comma-separated directory names to skip (default: node_modules,vendor,.git,dist,build,target,__pycache__,.venv,.next,coverage). Use empty string to skip no directories.
         */
        excludeDirs?: string;
        /**
         * Exclude hidden files and directories (default: true)
         */
        excludeHidden?: boolean;
    };
    url: '/filesystem-find/{path}';
};

export type GetFilesystemFindByPathErrors = {
    /**
     * Bad request
     */
    400: ErrorResponse;
    /**
     * Unprocessable entity
     */
    422: ErrorResponse;
    /**
     * Internal server error
     */
    500: ErrorResponse;
};

export type GetFilesystemFindByPathError = GetFilesystemFindByPathErrors[keyof GetFilesystemFindByPathErrors];

export type GetFilesystemFindByPathResponses = {
    /**
     * Find results
     */
    200: FindResponse;
};

export type GetFilesystemFindByPathResponse = GetFilesystemFindByPathResponses[keyof GetFilesystemFindByPathResponses];

export type GetFilesystemMultipartData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/filesystem-multipart';
};

export type GetFilesystemMultipartErrors = {
    /**
     * Internal server error
     */
    500: ErrorResponse;
};

export type GetFilesystemMultipartError = GetFilesystemMultipartErrors[keyof GetFilesystemMultipartErrors];

export type GetFilesystemMultipartResponses = {
    /**
     * List of active uploads
     */
    200: MultipartListUploadsResponse;
};

export type GetFilesystemMultipartResponse = GetFilesystemMultipartResponses[keyof GetFilesystemMultipartResponses];

export type DeleteFilesystemMultipartByUploadIdAbortData = {
    body?: never;
    path: {
        /**
         * Upload ID
         */
        uploadId: string;
    };
    query?: never;
    url: '/filesystem-multipart/{uploadId}/abort';
};

export type DeleteFilesystemMultipartByUploadIdAbortErrors = {
    /**
     * Bad request
     */
    400: ErrorResponse;
    /**
     * Upload not found
     */
    404: ErrorResponse;
    /**
     * Internal server error
     */
    500: ErrorResponse;
};

export type DeleteFilesystemMultipartByUploadIdAbortError = DeleteFilesystemMultipartByUploadIdAbortErrors[keyof DeleteFilesystemMultipartByUploadIdAbortErrors];

export type DeleteFilesystemMultipartByUploadIdAbortResponses = {
    /**
     * Upload aborted
     */
    200: SuccessResponse;
};

export type DeleteFilesystemMultipartByUploadIdAbortResponse = DeleteFilesystemMultipartByUploadIdAbortResponses[keyof DeleteFilesystemMultipartByUploadIdAbortResponses];

export type PostFilesystemMultipartByUploadIdCompleteData = {
    /**
     * List of parts
     */
    body: MultipartCompleteRequest;
    path: {
        /**
         * Upload ID
         */
        uploadId: string;
    };
    query?: never;
    url: '/filesystem-multipart/{uploadId}/complete';
};

export type PostFilesystemMultipartByUploadIdCompleteErrors = {
    /**
     * Bad request
     */
    400: ErrorResponse;
    /**
     * Upload not found
     */
    404: ErrorResponse;
    /**
     * Internal server error
     */
    500: ErrorResponse;
};

export type PostFilesystemMultipartByUploadIdCompleteError = PostFilesystemMultipartByUploadIdCompleteErrors[keyof PostFilesystemMultipartByUploadIdCompleteErrors];

export type PostFilesystemMultipartByUploadIdCompleteResponses = {
    /**
     * Upload completed
     */
    200: SuccessResponse;
};

export type PostFilesystemMultipartByUploadIdCompleteResponse = PostFilesystemMultipartByUploadIdCompleteResponses[keyof PostFilesystemMultipartByUploadIdCompleteResponses];

export type PutFilesystemMultipartByUploadIdPartData = {
    body: {
        /**
         * Part data
         */
        file: Blob | File;
    };
    path: {
        /**
         * Upload ID
         */
        uploadId: string;
    };
    query: {
        /**
         * Part number (1-10000)
         */
        partNumber: number;
    };
    url: '/filesystem-multipart/{uploadId}/part';
};

export type PutFilesystemMultipartByUploadIdPartErrors = {
    /**
     * Bad request
     */
    400: ErrorResponse;
    /**
     * Upload not found
     */
    404: ErrorResponse;
    /**
     * Internal server error
     */
    500: ErrorResponse;
};

export type PutFilesystemMultipartByUploadIdPartError = PutFilesystemMultipartByUploadIdPartErrors[keyof PutFilesystemMultipartByUploadIdPartErrors];

export type PutFilesystemMultipartByUploadIdPartResponses = {
    /**
     * Part uploaded
     */
    200: MultipartUploadPartResponse;
};

export type PutFilesystemMultipartByUploadIdPartResponse = PutFilesystemMultipartByUploadIdPartResponses[keyof PutFilesystemMultipartByUploadIdPartResponses];

export type GetFilesystemMultipartByUploadIdPartsData = {
    body?: never;
    path: {
        /**
         * Upload ID
         */
        uploadId: string;
    };
    query?: never;
    url: '/filesystem-multipart/{uploadId}/parts';
};

export type GetFilesystemMultipartByUploadIdPartsErrors = {
    /**
     * Bad request
     */
    400: ErrorResponse;
    /**
     * Upload not found
     */
    404: ErrorResponse;
    /**
     * Internal server error
     */
    500: ErrorResponse;
};

export type GetFilesystemMultipartByUploadIdPartsError = GetFilesystemMultipartByUploadIdPartsErrors[keyof GetFilesystemMultipartByUploadIdPartsErrors];

export type GetFilesystemMultipartByUploadIdPartsResponses = {
    /**
     * List of parts
     */
    200: MultipartListPartsResponse;
};

export type GetFilesystemMultipartByUploadIdPartsResponse = GetFilesystemMultipartByUploadIdPartsResponses[keyof GetFilesystemMultipartByUploadIdPartsResponses];

export type PostFilesystemMultipartInitiateByPathData = {
    /**
     * Optional permissions
     */
    body?: MultipartInitiateRequest;
    path: {
        /**
         * File path
         */
        path: string;
    };
    query?: never;
    url: '/filesystem-multipart/initiate/{path}';
};

export type PostFilesystemMultipartInitiateByPathErrors = {
    /**
     * Bad request
     */
    400: ErrorResponse;
    /**
     * Internal server error
     */
    500: ErrorResponse;
};

export type PostFilesystemMultipartInitiateByPathError = PostFilesystemMultipartInitiateByPathErrors[keyof PostFilesystemMultipartInitiateByPathErrors];

export type PostFilesystemMultipartInitiateByPathResponses = {
    /**
     * Upload session created
     */
    200: MultipartInitiateResponse;
};

export type PostFilesystemMultipartInitiateByPathResponse = PostFilesystemMultipartInitiateByPathResponses[keyof PostFilesystemMultipartInitiateByPathResponses];

export type GetFilesystemSearchByPathData = {
    body?: never;
    path: {
        /**
         * Path to search in (e.g., /home/user/projects)
         */
        path: string;
    };
    query?: {
        /**
         * Maximum number of results to return (default: 20)
         */
        maxResults?: number;
        /**
         * Comma-separated file patterns to include (e.g., *.go,*.js)
         */
        patterns?: string;
        /**
         * Comma-separated directory names to skip (default: node_modules,vendor,.git,dist,build,target,__pycache__,.venv,.next,coverage). Use empty string to skip no directories.
         */
        excludeDirs?: string;
        /**
         * Exclude hidden files and directories (default: true)
         */
        excludeHidden?: boolean;
    };
    url: '/filesystem-search/{path}';
};

export type GetFilesystemSearchByPathErrors = {
    /**
     * Bad request
     */
    400: ErrorResponse;
    /**
     * Unprocessable entity
     */
    422: ErrorResponse;
    /**
     * Internal server error
     */
    500: ErrorResponse;
};

export type GetFilesystemSearchByPathError = GetFilesystemSearchByPathErrors[keyof GetFilesystemSearchByPathErrors];

export type GetFilesystemSearchByPathResponses = {
    /**
     * Fuzzy search results
     */
    200: FuzzySearchResponse;
};

export type GetFilesystemSearchByPathResponse = GetFilesystemSearchByPathResponses[keyof GetFilesystemSearchByPathResponses];

export type DeleteFilesystemByPathData = {
    body?: never;
    path: {
        /**
         * File or directory path
         */
        path: string;
    };
    query?: {
        /**
         * Delete directory recursively
         */
        recursive?: boolean;
    };
    url: '/filesystem/{path}';
};

export type DeleteFilesystemByPathErrors = {
    /**
     * File or directory not found
     */
    404: ErrorResponse;
    /**
     * Unprocessable entity
     */
    422: ErrorResponse;
    /**
     * Internal server error
     */
    500: ErrorResponse;
};

export type DeleteFilesystemByPathError = DeleteFilesystemByPathErrors[keyof DeleteFilesystemByPathErrors];

export type DeleteFilesystemByPathResponses = {
    /**
     * Success message
     */
    200: SuccessResponse;
};

export type DeleteFilesystemByPathResponse = DeleteFilesystemByPathResponses[keyof DeleteFilesystemByPathResponses];

export type GetFilesystemByPathData = {
    body?: never;
    path: {
        /**
         * File or directory path
         */
        path: string;
    };
    query?: {
        /**
         * Force download mode for files
         */
        download?: boolean;
    };
    url: '/filesystem/{path}';
};

export type GetFilesystemByPathErrors = {
    /**
     * File or directory not found
     */
    404: ErrorResponse;
    /**
     * Unprocessable entity
     */
    422: ErrorResponse;
    /**
     * Internal server error
     */
    500: ErrorResponse;
};

export type GetFilesystemByPathError = GetFilesystemByPathErrors[keyof GetFilesystemByPathErrors];

export type GetFilesystemByPathResponses = {
    /**
     * Directory listing
     */
    200: Directory | FileWithContent | (Blob | File);
};

export type GetFilesystemByPathResponse = GetFilesystemByPathResponses[keyof GetFilesystemByPathResponses];

export type PutFilesystemByPathData = {
    /**
     * File or directory details
     */
    body: FileRequest;
    path: {
        /**
         * File or directory path
         */
        path: string;
    };
    query?: never;
    url: '/filesystem/{path}';
};

export type PutFilesystemByPathErrors = {
    /**
     * Bad request
     */
    400: ErrorResponse;
    /**
     * Unprocessable entity
     */
    422: ErrorResponse;
    /**
     * Internal server error
     */
    500: ErrorResponse;
};

export type PutFilesystemByPathError = PutFilesystemByPathErrors[keyof PutFilesystemByPathErrors];

export type PutFilesystemByPathResponses = {
    /**
     * Success message
     */
    200: SuccessResponse;
};

export type PutFilesystemByPathResponse = PutFilesystemByPathResponses[keyof PutFilesystemByPathResponses];

export type DeleteFilesystemTreeByPathData = {
    body?: never;
    path: {
        /**
         * Root directory path
         */
        path: string;
    };
    query?: {
        /**
         * Delete directory recursively
         */
        recursive?: boolean;
    };
    url: '/filesystem/tree/{path}';
};

export type DeleteFilesystemTreeByPathErrors = {
    /**
     * Bad request
     */
    400: ErrorResponse;
    /**
     * Unprocessable entity
     */
    422: ErrorResponse;
    /**
     * Internal server error
     */
    500: ErrorResponse;
};

export type DeleteFilesystemTreeByPathError = DeleteFilesystemTreeByPathErrors[keyof DeleteFilesystemTreeByPathErrors];

export type DeleteFilesystemTreeByPathResponses = {
    /**
     * Directory deleted successfully
     */
    200: SuccessResponse;
};

export type DeleteFilesystemTreeByPathResponse = DeleteFilesystemTreeByPathResponses[keyof DeleteFilesystemTreeByPathResponses];

export type GetFilesystemTreeByPathData = {
    body?: never;
    path: {
        /**
         * Root directory path
         */
        path: string;
    };
    query?: never;
    url: '/filesystem/tree/{path}';
};

export type GetFilesystemTreeByPathErrors = {
    /**
     * Bad request
     */
    400: ErrorResponse;
    /**
     * Unprocessable entity
     */
    422: ErrorResponse;
    /**
     * Internal server error
     */
    500: ErrorResponse;
};

export type GetFilesystemTreeByPathError = GetFilesystemTreeByPathErrors[keyof GetFilesystemTreeByPathErrors];

export type GetFilesystemTreeByPathResponses = {
    /**
     * Directory tree
     */
    200: Directory | FileWithContent | (Blob | File);
};

export type GetFilesystemTreeByPathResponse = GetFilesystemTreeByPathResponses[keyof GetFilesystemTreeByPathResponses];

export type PutFilesystemTreeByPathData = {
    /**
     * Map of file paths to content
     */
    body: TreeRequest;
    path: {
        /**
         * Root directory path
         */
        path: string;
    };
    query?: never;
    url: '/filesystem/tree/{path}';
};

export type PutFilesystemTreeByPathErrors = {
    /**
     * Bad request
     */
    400: ErrorResponse;
    /**
     * Unprocessable entity
     */
    422: ErrorResponse;
    /**
     * Internal server error
     */
    500: ErrorResponse;
};

export type PutFilesystemTreeByPathError = PutFilesystemTreeByPathErrors[keyof PutFilesystemTreeByPathErrors];

export type PutFilesystemTreeByPathResponses = {
    /**
     * Updated directory tree
     */
    200: Directory | FileWithContent | (Blob | File);
};

export type PutFilesystemTreeByPathResponse = PutFilesystemTreeByPathResponses[keyof PutFilesystemTreeByPathResponses];

export type GetHealthData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/health';
};

export type GetHealthResponses = {
    /**
     * Health status
     */
    200: HealthResponse;
};

export type GetHealthResponse = GetHealthResponses[keyof GetHealthResponses];

export type DeleteNetworkProcessByPidMonitorData = {
    body?: never;
    path: {
        /**
         * Process ID
         */
        pid: number;
    };
    query?: never;
    url: '/network/process/{pid}/monitor';
};

export type DeleteNetworkProcessByPidMonitorErrors = {
    /**
     * Invalid process ID
     */
    400: ErrorResponse;
    /**
     * Unprocessable entity
     */
    422: ErrorResponse;
    /**
     * Internal server error
     */
    500: ErrorResponse;
};

export type DeleteNetworkProcessByPidMonitorError = DeleteNetworkProcessByPidMonitorErrors[keyof DeleteNetworkProcessByPidMonitorErrors];

export type DeleteNetworkProcessByPidMonitorResponses = {
    /**
     * Object containing PID and success message
     */
    200: {
        [key: string]: unknown;
    };
};

export type DeleteNetworkProcessByPidMonitorResponse = DeleteNetworkProcessByPidMonitorResponses[keyof DeleteNetworkProcessByPidMonitorResponses];

export type PostNetworkProcessByPidMonitorData = {
    /**
     * Port monitor configuration
     */
    body: PortMonitorRequest;
    path: {
        /**
         * Process ID
         */
        pid: number;
    };
    query?: never;
    url: '/network/process/{pid}/monitor';
};

export type PostNetworkProcessByPidMonitorErrors = {
    /**
     * Invalid request
     */
    400: ErrorResponse;
    /**
     * Unprocessable entity
     */
    422: ErrorResponse;
    /**
     * Internal server error
     */
    500: ErrorResponse;
};

export type PostNetworkProcessByPidMonitorError = PostNetworkProcessByPidMonitorErrors[keyof PostNetworkProcessByPidMonitorErrors];

export type PostNetworkProcessByPidMonitorResponses = {
    /**
     * Object containing PID and success message
     */
    200: {
        [key: string]: unknown;
    };
};

export type PostNetworkProcessByPidMonitorResponse = PostNetworkProcessByPidMonitorResponses[keyof PostNetworkProcessByPidMonitorResponses];

export type GetNetworkProcessByPidPortsData = {
    body?: never;
    path: {
        /**
         * Process ID
         */
        pid: number;
    };
    query?: never;
    url: '/network/process/{pid}/ports';
};

export type GetNetworkProcessByPidPortsErrors = {
    /**
     * Invalid process ID
     */
    400: ErrorResponse;
    /**
     * Unprocessable entity
     */
    422: ErrorResponse;
    /**
     * Internal server error
     */
    500: ErrorResponse;
};

export type GetNetworkProcessByPidPortsError = GetNetworkProcessByPidPortsErrors[keyof GetNetworkProcessByPidPortsErrors];

export type GetNetworkProcessByPidPortsResponses = {
    /**
     * Object containing PID and array of network.PortInfo
     */
    200: {
        [key: string]: unknown;
    };
};

export type GetNetworkProcessByPidPortsResponse = GetNetworkProcessByPidPortsResponses[keyof GetNetworkProcessByPidPortsResponses];

export type DeleteNetworkTunnelData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/network/tunnel';
};

export type DeleteNetworkTunnelErrors = {
    /**
     * No tunnel is running
     */
    400: ErrorResponse;
    /**
     * Failed to stop tunnel
     */
    500: ErrorResponse;
};

export type DeleteNetworkTunnelError = DeleteNetworkTunnelErrors[keyof DeleteNetworkTunnelErrors];

export type DeleteNetworkTunnelResponses = {
    /**
     * Tunnel disconnected
     */
    200: SuccessResponse;
};

export type DeleteNetworkTunnelResponse = DeleteNetworkTunnelResponses[keyof DeleteNetworkTunnelResponses];

export type PutNetworkTunnelConfigData = {
    /**
     * Base64-encoded tunnel configuration
     */
    body: TunnelConfigRequest;
    path?: never;
    query?: never;
    url: '/network/tunnel/config';
};

export type PutNetworkTunnelConfigErrors = {
    /**
     * Invalid request body
     */
    400: ErrorResponse;
    /**
     * Invalid tunnel configuration
     */
    422: ErrorResponse;
    /**
     * Failed to apply configuration
     */
    500: ErrorResponse;
};

export type PutNetworkTunnelConfigError = PutNetworkTunnelConfigErrors[keyof PutNetworkTunnelConfigErrors];

export type PutNetworkTunnelConfigResponses = {
    /**
     * Configuration applied
     */
    200: SuccessResponse;
};

export type PutNetworkTunnelConfigResponse = PutNetworkTunnelConfigResponses[keyof PutNetworkTunnelConfigResponses];

export type GetProcessData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/process';
};

export type GetProcessResponses = {
    /**
     * Process list
     */
    200: Array<ProcessResponse>;
};

export type GetProcessResponse = GetProcessResponses[keyof GetProcessResponses];

export type PostProcessData = {
    /**
     * Process execution request
     */
    body: ProcessRequest;
    path?: never;
    query?: never;
    url: '/process';
};

export type PostProcessErrors = {
    /**
     * Invalid request
     */
    400: ErrorResponse;
    /**
     * Unprocessable entity
     */
    422: ErrorResponse;
    /**
     * Internal server error
     */
    500: ErrorResponse;
};

export type PostProcessError = PostProcessErrors[keyof PostProcessErrors];

export type PostProcessResponses = {
    /**
     * Process information
     */
    200: ProcessResponse;
};

export type PostProcessResponse = PostProcessResponses[keyof PostProcessResponses];

export type DeleteProcessByIdentifierData = {
    body?: never;
    path: {
        /**
         * Process identifier (PID or name)
         */
        identifier: string;
    };
    query?: never;
    url: '/process/{identifier}';
};

export type DeleteProcessByIdentifierErrors = {
    /**
     * Process not found
     */
    404: ErrorResponse;
    /**
     * Unprocessable entity
     */
    422: ErrorResponse;
    /**
     * Internal server error
     */
    500: ErrorResponse;
};

export type DeleteProcessByIdentifierError = DeleteProcessByIdentifierErrors[keyof DeleteProcessByIdentifierErrors];

export type DeleteProcessByIdentifierResponses = {
    /**
     * Process stopped
     */
    200: SuccessResponse;
};

export type DeleteProcessByIdentifierResponse = DeleteProcessByIdentifierResponses[keyof DeleteProcessByIdentifierResponses];

export type GetProcessByIdentifierData = {
    body?: never;
    path: {
        /**
         * Process identifier (PID or name)
         */
        identifier: string;
    };
    query?: never;
    url: '/process/{identifier}';
};

export type GetProcessByIdentifierErrors = {
    /**
     * Process not found
     */
    404: ErrorResponse;
};

export type GetProcessByIdentifierError = GetProcessByIdentifierErrors[keyof GetProcessByIdentifierErrors];

export type GetProcessByIdentifierResponses = {
    /**
     * Process information
     */
    200: ProcessResponse;
};

export type GetProcessByIdentifierResponse = GetProcessByIdentifierResponses[keyof GetProcessByIdentifierResponses];

export type DeleteProcessByIdentifierKillData = {
    body?: never;
    path: {
        /**
         * Process identifier (PID or name)
         */
        identifier: string;
    };
    query?: never;
    url: '/process/{identifier}/kill';
};

export type DeleteProcessByIdentifierKillErrors = {
    /**
     * Process not found
     */
    404: ErrorResponse;
    /**
     * Unprocessable entity
     */
    422: ErrorResponse;
    /**
     * Internal server error
     */
    500: ErrorResponse;
};

export type DeleteProcessByIdentifierKillError = DeleteProcessByIdentifierKillErrors[keyof DeleteProcessByIdentifierKillErrors];

export type DeleteProcessByIdentifierKillResponses = {
    /**
     * Process killed
     */
    200: SuccessResponse;
};

export type DeleteProcessByIdentifierKillResponse = DeleteProcessByIdentifierKillResponses[keyof DeleteProcessByIdentifierKillResponses];

export type GetProcessByIdentifierLogsData = {
    body?: never;
    path: {
        /**
         * Process identifier (PID or name)
         */
        identifier: string;
    };
    query?: never;
    url: '/process/{identifier}/logs';
};

export type GetProcessByIdentifierLogsErrors = {
    /**
     * Process not found
     */
    404: ErrorResponse;
    /**
     * Unprocessable entity
     */
    422: ErrorResponse;
    /**
     * Internal server error
     */
    500: ErrorResponse;
};

export type GetProcessByIdentifierLogsError = GetProcessByIdentifierLogsErrors[keyof GetProcessByIdentifierLogsErrors];

export type GetProcessByIdentifierLogsResponses = {
    /**
     * Process logs
     */
    200: ProcessLogs;
};

export type GetProcessByIdentifierLogsResponse = GetProcessByIdentifierLogsResponses[keyof GetProcessByIdentifierLogsResponses];

export type GetProcessByIdentifierLogsStreamData = {
    body?: never;
    path: {
        /**
         * Process identifier (PID or name)
         */
        identifier: string;
    };
    query?: never;
    url: '/process/{identifier}/logs/stream';
};

export type GetProcessByIdentifierLogsStreamErrors = {
    /**
     * Process not found
     */
    404: ErrorResponse;
    /**
     * Unprocessable entity
     */
    422: ErrorResponse;
    /**
     * Internal server error
     */
    500: ErrorResponse;
};

export type GetProcessByIdentifierLogsStreamError = GetProcessByIdentifierLogsStreamErrors[keyof GetProcessByIdentifierLogsStreamErrors];

export type GetProcessByIdentifierLogsStreamResponses = {
    /**
     * Stream of process logs, one line per log (prefixed with stdout:/stderr:)
     */
    200: string;
};

export type GetProcessByIdentifierLogsStreamResponse = GetProcessByIdentifierLogsStreamResponses[keyof GetProcessByIdentifierLogsStreamResponses];

export type DeleteProcessByIdentifierStdinData = {
    body?: never;
    path: {
        /**
         * Process identifier (PID or name)
         */
        identifier: string;
    };
    query?: never;
    url: '/process/{identifier}/stdin';
};

export type DeleteProcessByIdentifierStdinErrors = {
    /**
     * Process not found
     */
    404: ErrorResponse;
    /**
     * Process has no stdin
     */
    409: ErrorResponse;
};

export type DeleteProcessByIdentifierStdinError = DeleteProcessByIdentifierStdinErrors[keyof DeleteProcessByIdentifierStdinErrors];

export type DeleteProcessByIdentifierStdinResponses = {
    /**
     * Stdin closed
     */
    200: SuccessResponse;
};

export type DeleteProcessByIdentifierStdinResponse = DeleteProcessByIdentifierStdinResponses[keyof DeleteProcessByIdentifierStdinResponses];

export type PostProcessByIdentifierStdinData = {
    /**
     * Raw bytes to write
     */
    body: string;
    path: {
        /**
         * Process identifier (PID or name)
         */
        identifier: string;
    };
    query?: never;
    url: '/process/{identifier}/stdin';
};

export type PostProcessByIdentifierStdinErrors = {
    /**
     * Process not found
     */
    404: ErrorResponse;
    /**
     * Process has no stdin, or stdin is closed
     */
    409: ErrorResponse;
    /**
     * Body over 8 MiB
     */
    413: ErrorResponse;
    /**
     * Write failed
     */
    500: ErrorResponse;
    /**
     * Process stopped reading its stdin
     */
    503: ErrorResponse;
};

export type PostProcessByIdentifierStdinError = PostProcessByIdentifierStdinErrors[keyof PostProcessByIdentifierStdinErrors];

export type PostProcessByIdentifierStdinResponses = {
    /**
     * Bytes written
     */
    200: SuccessResponse;
};

export type PostProcessByIdentifierStdinResponse = PostProcessByIdentifierStdinResponses[keyof PostProcessByIdentifierStdinResponses];

export type PostUpgradeData = {
    /**
     * Upgrade options
     */
    body?: UpgradeRequest;
    path?: never;
    query?: never;
    url: '/upgrade';
};

export type PostUpgradeErrors = {
    /**
     * Internal server error
     */
    500: ErrorResponse;
};

export type PostUpgradeError = PostUpgradeErrors[keyof PostUpgradeErrors];

export type PostUpgradeResponses = {
    /**
     * Upgrade initiated
     */
    200: SuccessResponse;
};

export type PostUpgradeResponse = PostUpgradeResponses[keyof PostUpgradeResponses];

export type GetWatchFilesystemByPathData = {
    body?: never;
    path: {
        /**
         * Directory path to watch
         */
        path: string;
    };
    query?: {
        /**
         * Ignore patterns (comma-separated)
         */
        ignore?: string;
    };
    url: '/watch/filesystem/{path}';
};

export type GetWatchFilesystemByPathErrors = {
    /**
     * Invalid path
     */
    400: ErrorResponse;
    /**
     * Internal server error
     */
    500: ErrorResponse;
};

export type GetWatchFilesystemByPathError = GetWatchFilesystemByPathErrors[keyof GetWatchFilesystemByPathErrors];

export type GetWatchFilesystemByPathResponses = {
    /**
     * Stream of modified file paths, one per line
     */
    200: string;
};

export type GetWatchFilesystemByPathResponse = GetWatchFilesystemByPathResponses[keyof GetWatchFilesystemByPathResponses];

export type ClientOptions = {
    baseUrl: 'https://sbx-{sandbox_id}-{workspace_id}.{region}.bl.run' | (string & {});
};